services:
  eureka:
    image: iuha-messenger
    ports:
      - "8761:8761"

  mysql:
    container_name: mysql-container
    image: mysql:latest
    volumes:
      - ~/docker/mysql/iuha/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/iuha/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/iuha/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=iuhadb
      - MYSQL_USER=iuha
      - MYSQL_ROOT_PASSWORD=iuha
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    networks:
      - iuha-network

  redis:
    container_name: redis-container
    image: redis:latest
    command: redis-server
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - iuha-network

networks:
  iuha-network: